namespace Futurum.EventApiEndpoint.Metadata;

public record MetadataEnvelopeEventDefinition(MetadataSubscriptionEnvelopeEventDefinition MetadataSubscriptionEventDefinition, MetadataTypeDefinition MetadataTypeDefinition);